PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO User VALUES(3,'filip','JGFyZ29uMmlkJHY9MTkkbT02NTUzNix0PTIscD0xJG5PcWRVV3pubEgrckR6YzI4cFBNVkEkSGNkWFdvQ0NYUlFubTFGdGNRTFl5aEJwK2hoZHJkcFg1K09laW14ODVFTQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=');
INSERT INTO Category VALUES(1,'Food');
INSERT INTO Category VALUES(2,'Transport');
INSERT INTO Currency VALUES(1,'USD','$');
INSERT INTO Currency VALUES(2,'EUR','€');
INSERT INTO "Group" VALUES(1,'Wasp Retreat');
INSERT INTO GroupParticipant VALUES(1,1);
INSERT INTO GroupParticipant VALUES(1,2);
INSERT INTO GroupParticipant VALUES(1,4);
INSERT INTO GroupParticipant VALUES(1,3);
INSERT INTO Participant VALUES(1,'Filip Sodić','filip@wasp-lang.dev',3);
INSERT INTO Participant VALUES(2,'Shayne Czyzewski','shayne@wasp-lang.dev',NULL);
INSERT INTO Participant VALUES(3,'Martin Šošić','martin@wasp-lang.dev',NULL);
INSERT INTO Participant VALUES(4,'Matija Šošić','matija@wasp-lang.dev',NULL);
INSERT INTO Participant VALUES(5,'Joe Something','joe@gmail.com',NULL);
INSERT INTO ExpenseParticipant VALUES(0,1,1,1);
INSERT INTO ExpenseParticipant VALUES(0,0,1,2);
INSERT INTO Expense VALUES(1,'Lunch',1665140683014,1,1);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('User',3);
INSERT INTO sqlite_sequence VALUES('Category',2);
INSERT INTO sqlite_sequence VALUES('Currency',2);
INSERT INTO sqlite_sequence VALUES('Participant',5);
INSERT INTO sqlite_sequence VALUES('Group',1);
INSERT INTO sqlite_sequence VALUES('Expense',1);
COMMIT;
